== Environment Setup

Your environment has already been set up and you are ready to deploy your first ROSA cluster.

Your workshop environment consists of several components which have been pre-configured and are ready to use.
This includes a %aws_web_console_url%[Amazon Web Services (AWS)] account, and many other supporting resources.

ROSA is enabled on the AWS account used for this lab - and the ROSA CLI as well as AWS CLI tools are installed and configured on your bastion VM.

== Connect to your bastion VM

. In the terminal window to the right connect to the bastion VM (you can also just click the command below to have it copied and executed automatically):
+
[TIP]
====
Answer `yes` when asked if to accept the host key.

The password for the user %rosa_bastion_user_name% is `%rosa_user_password%`
====
+
[source,sh,role=execute]
----
ssh %rosa_bastion_user_name%@bastion.%rosa_subdomain_base%
----
+
.Click in the box below to copy and paste the string `yes` to your terminal:
+
[source,sh,role=execute]
----
yes
----
+
.Click in the box below to copy and paste the password to your terminal:
+
[source,sh,role=execute]
----
%rosa_user_password%
----

=== Validate installed tools

You will be using the `rosa`, `aws` and `oc` command line tools throughout this lab.

. Verify that the `rosa` command line tool is installed (note that your version may be a more recent version than the output shown below):
+
[source,sh,role=execute]
----
rosa version
----
+
.Sample Output
[source,texinfo]
----
1.2.22
Your ROSA CLI is up to date.
----

. Verify that the `aws` command line tool is installed:
+
[source,sh,role=execute]
----
aws --version
----
+
.Sample Output
[source,text,options=nowrap]
----
aws-cli/2.11.23 Python/3.11.3 Linux/4.18.0-305.88.1.el8_4.x86_64 exe/x86_64.rhel.8 prompt/off
----

. Verify that the `aws` command line tool is configured correctly:
+
[source,sh,role=execute]
----
aws sts get-caller-identity
----
+
.Sample Output
[source,texinfo]
----
{
    "UserId": "AIDA52VPS74UJLY4GUW7L",
    "Account": "950629760808",
    "Arn": "arn:aws:iam::950629760808:user/wkulhane@redhat.com-nhnv4"
}
----

. Verify that the `oc` CLI is installed correctly
+
[source,sh,role=execute]
----
rosa verify openshift-client
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Verifying whether OpenShift command-line tool is available...
I: Current OpenShift Client Version: 4.13.0
----

. Rosa login
+
[source,sh,role=execute]
----
rosa login
----
+
.Sample Output
[source,texinfo]
----
I: Logged in as 'rhpds-cloud' on 'https://api.openshift.com'
----
+
[NOTE]
====
Normally you would need to get a *token* from the https://console.redhat.com/openshift/token/rosa)[Red Hat Console] and log into ROSA using that token.

In this environment your token has been preconfigured for you.
====

. Run rosa whoami to verify your credentials:
+
[source,sh,role=execute]
----
rosa whoami
----
+
.Sample Output
[source,texinfo]
----
AWS ARN:                      arn:aws:iam::950629760808:user/wkulhane@redhat.com-nhnv4
AWS Account ID:               950629760808
AWS Default Region:           us-east-2
OCM API:                      https://api.openshift.com
OCM Account Email:            rhpds-admins+cloud@redhat.com
OCM Account ID:               1z8aXAxD3PWdlWiNRIE588rHD9l
OCM Account Name:             RHPDS Cloud
OCM Account Username:         rhpds-cloud
OCM Organization External ID: 15324659
OCM Organization ID:          1z8aXAQ73DYAPLeCZhNq1MRQ0ZL
OCM Organization Name:        Red Hat, Inc.
----

=== Verify quota

. Verify that your AWS account has enough quota in the region you will be deploying your cluster to.
+
[source,sh,role=execute]
----
rosa verify quota
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Validating AWS quota...
I: AWS quota ok. If cluster installation fails, validate actual AWS resource usage against https://docs.openshift.com/
rosa/rosa_getting_started/rosa-required-aws-service-quotas.html
----
+
See https://docs.openshift.com/rosa/rosa_planning/rosa-sts-required-aws-service-quotas.html[the documentation] for more details regarding quotas.

=== Ensure ELB service role exists

Run the following to check for the role and create it if it is missing.

[source,sh,role=execute]
----
aws iam get-role --role-name "AWSServiceRoleForElasticLoadBalancing" || aws iam create-service-linked-role --aws-service-name "elasticloadbalancing.amazonaws.com"
----

We have now successfully set up our account and environment and are ready to deploy our cluster.
