== Environment Setup

Your environment has already been set up and you are ready to deploy your first ROSA cluster.

ROSA is enabled on the AWS account used for this lab - and the ROSA CLI as well as AWS CLI tools are installed and configured on your bastion VM.

There are currently two supported credential methods when creating a ROSA cluster.
One method uses an IAM user with the _AdministratorAccess_ policy (only for the account using ROSA).
The other, more recent, and *recommended* method uses AWS STS.
Please see the section "xref:15-sts_explained.adoc[ROSA with STS Explained]" for a detailed explanation.
In this workshop we will only be using the STS method.

== Connect to your bastion VM

. In the terminal window to the right connect to the bastion VM (you can also just click the command below to have it copied and executed automatically):
+
[TIP]
====
Answer `yes` when asked if to accept the host key.

The password for the user %rosa_bastion_user_name% is `%rosa_user_password%`
====
+
[source,sh,role=execute]
----
ssh %rosa_bastion_user_name%@bastion.%rosa_subdomain_base%
----

=== Validate installed tools

You will be using the `rosa`, `aws` and `oc` command line tools throughout this lab.

. Verify that the `rosa` command line tool is installed:
+
[source,sh,role=execute]
----
rosa version
----
+
.Sample Output
[source,texinfo]
----
1.2.15
Your ROSA CLI is up to date.
----

. Verify that the `aws` command line tool is installed and configured:
+
[source,sh,role=execute]
----
aws sts get-caller-identity
----
+
.Sample Output
[source,texinfo]
----
{
    "UserId": "AIDA52VPS74UJLY4GUW7L",
    "Account": "950629760808",
    "Arn": "arn:aws:iam::950629760808:user/wkulhane@redhat.com-nhnv4"
}
----

. Download and install the oc binary
// don't use `rosa download oc` because it downloads latest 4.12:
+
[source,sh,role=execute]
----
cd $HOME
wget https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.12.9/openshift-client-linux.tar.gz

mkdir $HOME/bin
tar -xzvf $HOME/openshift-client-linux.tar.gz -C $HOME/bin
rm $HOME/openshift-client-linux.tar.gz

export PATH=$HOME/bin:$PATH
----
+
*Why use `oc` over `kubectl`* + Being Kubernetes, one can definitely use `kubectl` with their OpenShift cluster.
`oc` is specific to OpenShift in that it includes the standard set of features from `kubectl` plus additional support for OpenShift functionality. See https://docs.openshift.com/container-platform/latest/cli_reference/openshift_cli/usage-oc-kubectl.html[Usage of oc and kubectl commands] for more details.

. Rosa login
+
[source,sh,role=execute]
----
rosa login
----
+
.Sample Output
[source,texinfo]
----
I: Logged in as 'rhpds-cloud' on 'https://api.openshift.com'
----

. Run rosa whoami to verify your credentials:
+
[source,sh,role=execute]
----
rosa whoami
----
+
.Sample Output
[source,texinfo]
----
AWS ARN:                      arn:aws:iam::950629760808:user/wkulhane@redhat.com-nhnv4
AWS Account ID:               950629760808
AWS Default Region:           us-east-2
OCM API:                      https://api.openshift.com
OCM Account Email:            rhpds-admins+cloud@redhat.com
OCM Account ID:               1z8aXAxD3PWdlWiNRIE588rHD9l
OCM Account Name:             RHPDS Cloud
OCM Account Username:         rhpds-cloud
OCM Organization External ID: 15324659
OCM Organization ID:          1z8aXAQ73DYAPLeCZhNq1MRQ0ZL
OCM Organization Name:        Red Hat, Inc.
----

=== Ensure the ELB service role exists

Make sure that the service role for ELB already exists, otherwise the cluster deployment could fail.

. Run the following to check for the role and create it if it is missing.
+
[source,sh,role=execute]
----
aws iam get-role --role-name "AWSServiceRoleForElasticLoadBalancing" || aws iam create-service-linked-role --aws-service-name "elasticloadbalancing.amazonaws.com"
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
{
    "Role": {
        "Path": "/aws-service-role/elasticloadbalancing.amazonaws.com/",
        "RoleName": "AWSServiceRoleForElasticLoadBalancing",
        "RoleId": "AROA5ZWLJ2BAZWKPE75AN",
        "Arn": "arn:aws:iam::948540395585:role/aws-service-role/elasticloadbalancing.amazonaws.com/AWSServiceRoleForEl
asticLoadBalancing",
        "CreateDate": "2019-09-07T14:48:48Z",
        "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Service": "elasticloadbalancing.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                }
            ]
        },
        "Description": "Allows ELB to call AWS services on your behalf.",
        "MaxSessionDuration": 3600,
        "RoleLastUsed": {
            "LastUsedDate": "2023-04-05T18:53:02Z",
            "Region": "us-east-2"
        }
    }
}
----

=== Verify quota

. Verify that your AWS account has enough quota in the region you will be deploying your cluster to.
+
[source,sh,role=execute]
----
rosa verify quota
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Validating AWS quota...
I: AWS quota ok. If cluster installation fails, validate actual AWS resource usage against https://docs.openshift.com/
rosa/rosa_getting_started/rosa-required-aws-service-quotas.html
----
+
See https://docs.openshift.com/rosa/rosa_planning/rosa-sts-required-aws-service-quotas.html[the documentation] for more details regarding quotas.

=== Verify `oc` CLI

. Verify that the `oc` CLI is installed correctly (remember that you installed the oc client before).
+
[source,sh,role=execute]
----
rosa verify openshift-client
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Verifying whether OpenShift command-line tool is available...
I: Current OpenShift Client Version: 4.12.9
----

We have now successfully set up our account and environment and are ready to deploy our cluster.

=== Cluster Deployment

In the next section you will deploy your cluster.
