== Introduction

When deploying your ROSA cluster, you can configure many aspects of your worker nodes, but what happens when you need to change your worker nodes after they've already been created?
These activities include scaling the number of nodes, changing the instance type, adding labels or taints, just to name a few.

Many of these changes are done using MachinePools.
MachinePools ensure that a specified number of Machine replicas are running at any given time.
Think of a MachinePool as a "template" for the kinds of Machines that make up the worker nodes of your cluster.
If you'd like to learn more, see the https://docs.openshift.com/rosa/rosa_cluster_admin/rosa_nodes/rosa-managing-worker-nodes.html[Red Hat documentation on worker node management].

== Scaling worker nodes

=== Via the CLI

. First, let's examine the MachineSets that are deployed in our cluster:
+
[source,sh,role=execute]
----
oc -n openshift-machine-api get machinesets
----
+
.Sample Output
[source,text,options=nowrap]
----
NAME                                   DESIRED   CURRENT   READY   AVAILABLE   AGE
rosa-6n4s8-7hbhw-infra-us-east-2a      2         2         2       2           22h
rosa-6n4s8-7hbhw-worker-us-east-2a     2         2         2       2           23h
----
+
You will see two MachineSets, one for worker nodes and one for infra nodes.

. It is best to manage the worker nodes using ROSA MachinePools. Let's see what MachinePools already exist in our cluster.
To do so, run the following command:
+
[source,sh,role=execute]
----
rosa list machinepools -c rosa-${GUID}
----
+
.Sample Output
[source,text,options=nowrap]
----
ID       AUTOSCALING  REPLICAS  INSTANCE TYPE  LABELS    TAINTS    AVAILABILITY ZONES    SUBNETS    SPOT INSTANCES
Default  No           2         m5.xlarge                          us-east-2a                       N/A
----
+
Note that there is only a MachinePool for worker nodes.

. Now, let's take a look at the machines inside of the ROSA cluster that have been created according to the instructions provided by the above MachinePools.
To do so, run the following command:
+
[source,sh,role=execute]
----
oc -n openshift-machine-api get machine
----
+
.Sample Output
[source,text,options=nowrap]
----
NAME                                       PHASE     TYPE         REGION      ZONE         AGE
rosa-6n4s8-7hbhw-infra-us-east-2a-bgr86    Running   r5.xlarge    us-east-2   us-east-2a   22h
rosa-6n4s8-7hbhw-infra-us-east-2a-xthr6    Running   r5.xlarge    us-east-2   us-east-2a   22h
rosa-6n4s8-7hbhw-master-0                  Running   m5.2xlarge   us-east-2   us-east-2a   23h
rosa-6n4s8-7hbhw-master-1                  Running   m5.2xlarge   us-east-2   us-east-2a   23h
rosa-6n4s8-7hbhw-master-2                  Running   m5.2xlarge   us-east-2   us-east-2a   23h
rosa-6n4s8-7hbhw-worker-us-east-2a-xc8g2   Running   m5.xlarge    us-east-2   us-east-2a   22h
rosa-6n4s8-7hbhw-worker-us-east-2a-zxm8j   Running   m5.xlarge    us-east-2   us-east-2a   22h
----
+
For this workshop, we've deployed your ROSA cluster with seven total machines (two workers, three control planes, and two infrastructure nodes).

. Now that we know that we have two worker nodes, let's create a MachinePool to add a new worker node using the ROSA CLI.
To do so, run the following command:
+
[source,sh,role=execute]
----
rosa create machinepool -c rosa-${GUID} --replicas 1 --name workshop --instance-type m5.xlarge
----
+
.Sample Output
[source,text,options=nowrap]
----
I: Fetching instance types
I: Machine pool 'workshop' created successfully on cluster 'rosa-6n4s8'
I: To view all machine pools, run 'rosa list machinepools -c rosa-6n4s8'
----
+
This command adds a single m5.xlarge instance to the {{ aws_region }}a availability zone.

. Now, let's scale up our selected MachinePool from one to two machines.
To do so, run the following command:
+
[source,sh,role=execute]
----
rosa update machinepool -c rosa-${GUID} --replicas 2 workshop
----
+
.Sample Output
[source,text,options=nowrap]
----
I: Updated machine pool 'workshop' on cluster 'rosa-6n4s8'
----

. Now that we've scaled the MachineSet to two machines, we can see that the machine is already being created.
First, let's quickly check the output of the same command we ran in step 1:
+
[source,sh,role=execute]
----
oc -n openshift-machine-api get machinesets
----
+
.Sample Output
[source,text,options=nowrap]
----
NAME                                   DESIRED   CURRENT   READY   AVAILABLE   AGE
rosa-6n4s8-7hbhw-infra-us-east-2a      2         2         2       2           22h
rosa-6n4s8-7hbhw-worker-us-east-2a     2         2         2       2           23h
rosa-6n4s8-7hbhw-workshop-us-east-2a   2         2                             70s
----

 Note, that the number of *desired* and *current* nodes matches the scale we specified, but depending when you ran this command they may not be available yet.

. We can also run the same command we ran in step 2 to see the machine being provisioned:
+
[source,sh,role=execute]
----
oc -n openshift-machine-api get machine
----
+
.Sample Output
[source,text,options=nowrap]
----
NAME                                         PHASE         TYPE         REGION      ZONE         AGE
rosa-6n4s8-7hbhw-infra-us-east-2a-bgr86      Running       r5.xlarge    us-east-2   us-east-2a   22h
rosa-6n4s8-7hbhw-infra-us-east-2a-xthr6      Running       r5.xlarge    us-east-2   us-east-2a   22h
rosa-6n4s8-7hbhw-master-0                    Running       m5.2xlarge   us-east-2   us-east-2a   23h
rosa-6n4s8-7hbhw-master-1                    Running       m5.2xlarge   us-east-2   us-east-2a   23h
rosa-6n4s8-7hbhw-master-2                    Running       m5.2xlarge   us-east-2   us-east-2a   23h
rosa-6n4s8-7hbhw-worker-us-east-2a-xc8g2     Running       m5.xlarge    us-east-2   us-east-2a   23h
rosa-6n4s8-7hbhw-worker-us-east-2a-zxm8j     Running       m5.xlarge    us-east-2   us-east-2a   23h
rosa-6n4s8-7hbhw-workshop-us-east-2a-pcfd9   Provisioned   m5.xlarge    us-east-2   us-east-2a   3m57s
rosa-6n4s8-7hbhw-workshop-us-east-2a-pxnvd   Provisioned   m5.xlarge    us-east-2   us-east-2a   4m30s
----

. Repeat the above command until all machines are in the *Running* phase. This means that they are ready and available to run Pods in the cluster.

. We don't actually need these extra worker nodes so let's scale the cluster back down to a total of 3 worker nodes by scaling down the "Workshop" Machine Pool.
To do so, run the following command:
+
----
rosa update machinepool -c rosa-${GUID} --replicas 1 workshop
----

. Now that we've scaled the MachinePool (and therefore the MachineSet) back down to one machine, we can see the change reflected in the cluster almost immediately.
Let's quickly check the output of the same command we ran before:
+
[source,sh,role=execute]
----
oc -n openshift-machine-api get machinesets
----
+
.Sample Output
[source,text,options=nowrap]
----
NAME                                   DESIRED   CURRENT   READY   AVAILABLE   AGE
rosa-6n4s8-7hbhw-infra-us-east-2a      2         2         2       2           22h
rosa-6n4s8-7hbhw-worker-us-east-2a     2         2         2       2           23h
rosa-6n4s8-7hbhw-workshop-us-east-2a   1         1         1       1           6m49s
----

. Now let's scale the cluster back down to a total of 2 worker nodes by deleting the "Workshop" Machine Pool.
To do so, run the following command:
+
[source,sh,role=execute]
----
rosa delete machinepool -c rosa-${GUID} workshop --yes
----
+
.Sample Output
[source,text,options=nowrap]
----
I: Successfully deleted machine pool 'workshop' from cluster 'rosa-6n4s8'
----

Congratulations!
You've successfully scaled your cluster up and back down to two worker nodes.
